name: Build pages

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v2
      with:
        python-version: '3.10'
        cache: 'pip'
        cache-dependency-path: '.jb/requirements.txt'
    - name: Install Jupyter Book Dependencies
      run: pip install -r .jb/requirements.txt
    - name: Build website
      run: jupyter-book build docs
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3.8.0
      if: github.ref == 'refs/heads/main'
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        force_orphan: true
        publish_dir: docs/_build/html
