name: Check markdown links

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"  # Every month

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.10'
          cache: 'pip'
          cache-dependency-path: '.jb/requirements.txt'
      - name: Install Jupyter Book Dependencies
        run: pip install -r .jb/requirements.txt
      - name: Check external links
        run: jupyter-book build docs --builder linkcheck
