name: Auto update notebooks

env:
  JULIA_VERSION: '1.7'
  PYTHON_VERSION: '3.10'

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * 1"  # Every Monday

jobs:
  update-notebook:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: julia-actions/cache-artifacts@v1
      - name: Setup Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ env.JULIA_VERSION }}
      - uses: actions/setup-python@v2
        with:
          python-version: ${{ env.PYTHON_VERSION }}
          cache: 'pip'
          cache-dependency-path: 'requirements.txt'
      - name: Install Python dependencies
        run:  pip install -r requirements.txt
      - name: Install IJulia
        env:
          PYTHON : python
        shell: julia --color=yes --threads=auto {0}
        run: |
          using Pkg
          Pkg.add("IJulia")
          Pkg.build("IJulia")
      - name: Update Julia dependencies
        env:
          PYTHON : python
        shell: julia --color=yes --threads=auto {0}
        run: |
          import Pkg
          Pkg.activate(".")
          Pkg.update()
      - name: Execute notebooks
        run: |
          find . -type f -name "*.ipynb" -print0 | parallel -0 -j2 jupyter nbconvert --to notebook --ExecutePreprocessor.timeout=600 --ExecutePreprocessor.kernel_name=julia-${JULIA_VERSION} --execute --inplace {}
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v3
        with:
          labels: |
            automerge
